title = "grimmle's cookbook"
baseURL = "https://grimmle.github.io/static-site"
publishDir = "docs"
languageCode = "de"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 10

[params]
  custom_css = ["css/main.css"] 
  favicon = ""
  site_logo = ""
  github = ""
  gitlab = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  recent_posts_number = 10
