title = "Lennard Grimm"
baseURL = "https://grimmle.github.io/cookbook"
publishDir = "docs"
languageCode = "de"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[params]
  custom_css = ["css/main.css"] 
  favicon = ""
  site_logo = ""
  github = ""
  gitlab = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10
